
provisioning:
  enabled: true

  image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 2.7.0-debian-10-r34
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits: 
      cpu: 250m
      memory: 1Gi
    requests: 
      cpu: 250m
      memory: 256Mi

  topics: 
    - name: test-topic
      partitions: 1
      replicationFactor: 1
    - name: item-request
      partitions: 1
      replicationFactor: 1
    - name: item-reply
      partitions: 1
      replicationFactor: 1
    - name: user-request
      partitions: 1
      replicationFactor: 1
    - name: user-replay
      partitions: 1
      replicationFactor: 1
    - name: order-request
      partitions: 1
      replicationFactor: 1
    - name: order-replay
      partitions: 1
      replicationFactor: 1
  # - name: topic-name
  #   partitions: 1
  #   replicationFactor: 1
  #   # https://kafka.apache.org/documentation/#topicconfigs
  #   config:
  #     max.message.bytes: 64000
  #     flush.messages: 1

